### PR TITLE
Improve display of HUI data

### PR DESCRIPTION
**Pull request by echaidemenos**
Fixes https://github.com/aqualinkorg/aqualink-app/issues/978

This PR:
 - Adds source to charts' tooltip label
 - Displays one year of data if there are extra sensors (instead of 1 month)
 -  Fixes graphs not showing lines due to date being spaced out in months
 - Adds an option to adapt timestamp to site's timezone in data uploads
 - Fetches and show raw HUI data, not hourly
 - Adds min max dates per site for uploads

### CODE REVIEW

**Comment by echaidemenos** [comment]
hello @ericboucher @Caesarh97 
A deployed version of these changes can be found here: https://aqualink-app-programize.web.app/sites/1704
I have included a copy of all affected sites. Here is the modified version of the uploads CSV i used.
[reefs-for-programize-hui.csv](https://github.com/aqualinkorg/aqualink-app/files/15025627/reefs-for-programize-hui.csv)

**Comment by Caesarh97** [comment]
> hello @ericboucher @Caesarh97 A deployed version of these changes can be found here: https://aqualink-app-programize.web.app/sites/1704 I have included a copy of all affected sites. Here is the modified version of the uploads CSV i used. [reefs-for-programize-hui.csv](https://github.com/aqualinkorg/aqualink-app/files/15025627/reefs-for-programize-hui.csv)

Hello @echaidemenos and @ericboucher,
Good job on this request! I have a couple of comments.

- The start date and end date when clicking on "VIEW UPLOAD" are still fixed at 2016-06-14 and 2023-12-07. Is this correct? If so, would it be possible for it to automatically adjust depending on when the first and last data points were added? 

Additional questions:
- It looks good when you added "NOAA" on the graph for surface temperature. However, I'm wondering if people still understand that it's satellite data from NOAA. Do you think it might be better to change it to "NOAA satellite data" or NOAA satellite"? Or would that be too long? 
- A new question: In the image below, you can see that the box with data is slightly to the right of the point that you want to look at. Would it be possible to change it so that it hovers straight above the point and not to the right? This would be for all sites and not just HUI. 

Screenshot 2024-04-18 at 5 48 31 PM
Screenshot 2024-04-18 at 5 49 24 PM

**Comment by echaidemenos** [comment]
Hello @Caesarh97 @ericboucher 
I have updated it so we keep the min and max date, of an upload, per site as well. The upload must be re done, for this to take effect:  
https://aqualink-app-programize.web.app/sites/1704

**Review by ericboucher — APPROVED** [review]

**Comment by Caesarh97** [comment]
> Hello @Caesarh97 @ericboucher I have updated it so we keep the min and max date, of an upload, per site as well. The upload must be re done, for this to take effect: https://aqualink-app-programize.web.app/sites/1704

@echaidemenos Sorry, I haven't seen the comment until now. Good job, and thank you! I can see that you changed the location of the box when hovering over the data in the graphs as well. Before, we had a little circle marking the data that you're hovering over. Would it be possible to keep the circle and have the box appear above the circle instead (maybe 10-15px above)? That would make it easier when looking at the data. Please only do this change if it's a relatively quick fix. 

Untitled design (30)

**Comment by ericboucher** [comment]
@Caesarh97 do you remember when you saw that circle? I don't remember seeing it recently?

**Comment by Caesarh97** [comment]
@ericboucher It's a little bit sensitive, but it still appears. 


https://github.com/aqualinkorg/aqualink-app/assets/113801743/88bf8e07-e126-44e0-b62c-cf863f692654

**Comment by ericboucher** [comment]
@Caesarh97 I tried to make it a bit less sensitive, can you give it a go? https://aqualink-app-987.surge.sh/

**Comment by Caesarh97** [comment]
@ericboucher It's perfect! Thanks, Eric.

**Pull request merged**
