### PR TITLE
Add global /api/ prefix to our API URL

### PR DESCRIPTION
**Pull request by avalmas-programize**
Add global prefix `api`
Rerouted swagger docs to `api/docs`

Breaking changes:
We need to make sure to update all env variables on all instances to comply this the above change
- Front-end env
- Firebase functions env
- Tests env (circleCI)

### CODE REVIEW

**Review by Ry-DS — APPROVED** [review]
LGTM!

**Comment by ericboucher** [comment]
@avalmas-programize how did the test go?

**Comment by avalmas-programize** [comment]
The following changes should be done to successfully deploy the above changes:
- Change `BACKEND_BASE_URL` backend env variable: Add `api/` suffix
- Change `api.base_url` firebase env variable: Add `api/` suffix
- Change `REACT_APP_API_BASE_URL` frontend env variable: Add `api/` suffix

The tailing `/` is mandatory.

**Comment by avalmas-programize** [comment]
I have added a check for the ping Service so the trailing `\` is no longer necessary

**Review by ericboucher — APPROVED** [review]

**Comment by avalmas-programize** [comment]
Added redirection from /api to /api/docs

**Comment by avalmas-programize** [comment]
Redeployed, and everything seems to work

**Pull request merged**
