### PR TITLE
Update react router usage to v6; fix minor issue

### LINKED ISSUE #1019: Change link for Dashboard button
Can we change the link when you click on “Dashboard”? (See image below) Note: Only change the link when you have not bookmarked any sites yet. The new link should go to: https://highlights.aqualink.org/learn-more/get-started-with-aqualink#h.49zi97uifdjf

Option 2 would be to have the same link as now (/tracker) but add an anchor tag for this section, "Create Your Dashboard" (see second image). 

Both options are fine for me. @ericboucher Please choose whatever you think would be best. 

Screenshot 2024-09-13 at 11 44 52 AM

Screenshot 2024-09-13 at 11 53 26 AM

### LINKED ISSUE #1020: Display latest data upload on Sonde dashboard card
When uploading water quality data for the Sonde dashboard card, the oldest data upload is showing. We should display the latest data point in the dashboard card. In [https://aqualink.org/sites/2188](https://aqualink.org/sites/2188), for example, the data upload with the data from 2022 is appearing. I’ve uploaded data in another upload that has data points from 2024. The most recent data points should populate the dashboard card. 

Screenshot 2024-09-13 at 12 00 15 PM

### PR DESCRIPTION
**Pull request by yaodingyd**
fix #1019
fix #1020 

/claim #1019
/claim #1020

1. The major change is to update react-router to v6, a lot of breaking changes includes
2.  use link `[highlights.aqualink.org/learn-more/get-started-with-aqualink#h.49zi97uifdjf](https://highlights.aqualink.org/learn-more/get-started-with-aqualink#h.49zi97uifdjf)` for dashboard
3. Update util to sort Sonda data to display the latest upload

Screenshot 2024-09-19 at 10 26 51 PM

### CODE REVIEW

**Comment by ericboucher** [comment]
@yaodingyd thanks for your PR! It looks great.  Just a few things to iron out:

I deployed your PR to https://aqualink-app-programize.web.app

When I click on the Dashboard link, I get sent to https://aqualink-app-programize.web.app/dashboard/https://highlights.aqualink.org/learn-more/get-started-with-aqualink#h.49zi97uifdjf which is an invalid link.

And it does not seem to take the time to know if I have previously saved sites or not. Could you look into that?

**Comment by yaodingyd** [comment]
@ericboucher just pushed a fix, could you try again?

**Comment by ericboucher** [comment]
It's slightly better but it does not fix the issue completely. I redeployed to the same link.

In my account I have a site saved, so I do have a collection:
Screenshot 2024-09-23 at 10 36 34 PM

But when I click on "Dashboard" it also opens the link to "highlights" in a new window. Feel free to create an account on the deployed website and test for yourself :)

**Comment by yaodingyd** [comment]
is there a way to run this locally? I would need a REACT_APP_FIREBASE_API_KEY env vars? debugging in the deployed site is impossible since js files are minified

**Comment by yaodingyd** [comment]
Got a firebase api key from prod and it works fine locally

it should be working now: the first part is  show dashboards when there's any; second part is to redirect


https://github.com/user-attachments/assets/e0459de6-c990-40a0-ab01-d3233d945133

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
