### PR TITLE
Api docs examples

### PR DESCRIPTION
**Pull request by avalmas-programize**
Add better examples to api docs

### CODE REVIEW

**Comment by ericboucher** [comment]
Could you add a few screenshots of the API docs with the examples setup?

**Comment by avalmas-programize** [comment]
Posting screenshots of examples in api docs

Added examples on all url and query params
image

Added examples on all body parameters
image

**Comment by avalmas-programize** [comment]
@ericboucher  Changes have been deployed on programize staging if you want to have a closer look

**Comment by ericboucher** [comment]
Looks good overall. Instead of using "some reef name" or "new reef name", let's use a real reef name. Eg. `Duxbury Reef`

**Comment by ericboucher** [comment]
@avalmas-programize is this PR ready for review?

**Comment by avalmas-programize** [comment]
Yes  this is ready for review

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
