### PR TITLE
Replace daily data with time series on reef map

### PR DESCRIPTION
**Pull request by avalmas-programize**
Replace daily data on reef entity with the time series data
Front-end changes needed: Get latest data from collectionData for map page

### CODE REVIEW

**Comment by ericboucher** [comment]
Is this ready for review? @avalmas-programize

**Comment by ericboucher** [comment]
I am not sure I understand why we are using `collectionData` here.
Also, the idea is to get the data in the table from the time series data as well

**Comment by avalmas-programize** [comment]
Amended SST script to backfill both degree heating weeks and alert level (daily and weekly)
Rewrote collection util `getCollectionData` to include data only from the `latestData` table
Breaking Front-end changes:
CollectionDataDto is based now on the metrics enum so the keys have been changed (from camelCase to snakeCase)

**Comment by ericboucher** [comment]
@avalmas-programize I deployed on programize. It looks good overall but it feels like the `/map` page is a lot slower than before. Could investigate and see where things are slow?

**Review by ericboucher — APPROVED** [review]

**Comment by ericboucher** [comment]
@avalmas-programize can you confirm which backfills we should be running right after this deploy?

**Comment by avalmas-programize** [comment]
We will need to run the sst_backfill script to backfill for dhw, alert, weekly_alert and sst_anomaly

**Pull request merged**
